# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4437e0a71fb092a9659aeb8d45047a5cb4a14713ea4c0070a5f6f07a6e6fa5eb1f7111f66fb7627caa78ef4ce4f254727fff6be4fcb55623be53065fa0e3c7b

test:
  secret_key_base: 0ce91ad424eadbc61cc7c8871d9e2c52ede2184787a12c92741abfd6ac7ffa25ebcbc2ed15722623db1fd7db872be95a093b9da7d6a7c02e7726686e4a12730b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
